// AUTH types
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH = 'SET_AUTH';

// HOTELS types
export const GET_HOTELS = 'GET_HOTELS';
export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
export const GET_HOTELS_FAILURE = 'GET_HOTELS_FAILURE';

export const GET_ONE_HOTEL = 'GET_ONE_HOTEL';
export const GET_ONE_HOTEL_SUCCESS = 'GET_ONE_HOTEL_SUCCESS';
export const GET_ONE_HOTEL_FAILURE = 'GET_ONE_HOTEL_FAILURE';

export const GET_HOTEL_REVIEWS = 'GET_HOTEL_REVIEWS';
export const GET_HOTEL_REVIEWS_SUCCESS = 'GET_HOTEL_REVIEWS_SUCCESS';
export const GET_HOTEL_REVIEWS_FAILURE = 'GET_HOTEL_REVIEWS_FAILURE';

// FAVORITES HOTELS types
export const GET_FAVORITES = 'GET_FAVORITES';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_FAILURE = 'GET_FAVORITES_FAILURE';

export const POST_FAVORITE = 'POST_FAVORITE';
export const POST_FAVORITE_SUCCESS = 'POST_FAVORITE_SUCCESS';
export const POST_FAVORITE_FAILURE = 'POST_FAVORITE_FAILURE';
